/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenant-server/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant server customer */
        post: operations["post-tenant-server-customer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-server/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant server customers */
        get: operations["get-tenant-server-customers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-server/gocardless/cancel/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant server gocardless cancel by environment */
        post: operations["post-tenant-server-gocardless-cancel-by-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-server/stripe/cancel/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant server stripe cancel by environment */
        post: operations["post-tenant-server-stripe-cancel-by-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-server/v2/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant server v2 customer */
        post: operations["post-tenant-server-v2-customer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/entitlements/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant entitlements active */
        post: operations["post-tenant-entitlements-active"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/entitlements/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant entitlements by environment */
        get: operations["get-tenant-entitlements-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/gocardless/billing-request-flow/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant gocardless billing request flow by environment */
        post: operations["post-tenant-gocardless-billing-request-flow-by-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/gocardless/products/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant gocardless products by environment */
        get: operations["get-tenant-gocardless-products-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant identify */
        post: operations["post-tenant-identify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant offerings */
        get: operations["get-tenant-offerings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/playstore/sync-purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant playstore sync purchases */
        post: operations["post-tenant-playstore-sync-purchases"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant products */
        get: operations["get-tenant-products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/stripe/checkout/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant stripe checkout by environment */
        post: operations["post-tenant-stripe-checkout-by-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/stripe/products/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant stripe products by environment */
        get: operations["get-tenant-stripe-products-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/subscriptions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant subscriptions active */
        post: operations["post-tenant-subscriptions-active"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerEntitlement: {
            id: string;
            name: string;
            status?: string;
            store?: string;
        };
        CustomerEntitlements: {
            customer_id: string;
            email: string;
            purchases: components["schemas"]["PurchaseItem"][] | null;
            subscriptions: components["schemas"]["SubscriptionItem"][] | null;
        };
        CustomerListItem: {
            customer_id: string;
            email: string;
            entitlements: components["schemas"]["CustomerEntitlement"][] | null;
            products: components["schemas"]["CustomerProduct"][] | null;
            status: string;
        };
        CustomerProduct: {
            id: string;
            name: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GetCustomerExtendedInfoByEmailRow: {
            email: string;
            email_sha256_sum: string | null;
            entitlement_name: string | null;
            entitlement_type: string | null;
            id: string;
            product_id: string | null;
            product_name: string | null;
            status: string | null;
            store: string | null;
        };
        ListCustomerResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListCustomerResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["PaginatedCustomers"];
            error?: string;
        };
        PaginatedCustomers: {
            customers: components["schemas"]["CustomerListItem"][] | null;
            /** Format: int64 */
            limit: number;
            next_cursor?: string;
            /** Format: int64 */
            total?: number;
        };
        PlayStorePastPurchase: {
            product_id: string;
            purchase_id: string;
            purchase_token: string;
            transaction_date: string;
        };
        PurchaseItem: {
            entitlement_id: string;
            entitlement_name: string;
            entitlement_type: string;
            product_id: string;
            product_name: string;
            purchase_state: string;
            status: string;
            store: string;
        };
        StorableEntitlement: {
            entitlement_id: string;
            entitlement_type: string;
            /** Format: int64 */
            expires_at: number;
            id: string;
            product_id: string;
            purchase_state?: string;
            renewal_status?: string;
            status: string;
            store: string;
            /** Format: int64 */
            trial_expires_at: number | null;
        };
        StorableSubscription: {
            entitlement_id: string;
            /** Format: int64 */
            expires_at: number;
            id: string;
            product_id: string;
            renewal_status: string;
            status: string;
            store: string;
            /** Format: int64 */
            trial_expires_at: number | null;
        };
        SubscriptionGocardlessProduct: {
            currency: string;
            description?: string;
            formatted_price: string;
            id: string;
            name: string;
            /** Format: int32 */
            price: number;
        };
        SubscriptionItem: {
            entitlement_id: string;
            entitlement_name: string;
            entitlement_type: string;
            product_id: string;
            product_name: string;
            status: string;
            store: string;
        };
        SubscriptionStripePrice: {
            currency: string;
            formattedPrice: string;
            id: string;
            /** Format: int32 */
            price: number;
            unitLabel: string;
        };
        SubscriptionStripeProduct: {
            active: boolean;
            /** Format: int64 */
            created: number;
            deleted?: boolean;
            description?: string;
            id: string;
            images: string[] | null;
            livemode: boolean;
            metadata: {
                [key: string]: string;
            };
            name: string;
            object: string;
            price: components["schemas"]["SubscriptionStripePrice"];
            shippable?: boolean;
            statement_descriptor?: string;
            type: string;
            unit_label?: string;
            /** Format: int64 */
            updated: number;
            url?: string;
        };
        TenantActiveEntitlementsInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveEntitlementsInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            /** @default prod */
            environment: string | null;
        };
        TenantActiveEntitlementsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveEntitlementsResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["StorableEntitlement"][] | null;
            error?: string;
        };
        TenantActiveSubscriptionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveSubscriptionInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            /** @default prod */
            environment: string | null;
        };
        TenantActiveSubscriptionResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveSubscriptionResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["StorableSubscription"];
            error?: string;
        };
        TenantCancelGoCardlessSubscriptionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantCancelGoCardlessSubscriptionInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            entitlement_id: string;
        };
        TenantCancelGoCardlessSubscriptionResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantCancelGoCardlessSubscriptionResponseBody.json
             */
            readonly $schema?: string;
            error?: string;
        };
        TenantCancelStripeSubscriptionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantCancelStripeSubscriptionInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            entitlement_id: string;
        };
        TenantCancelStripeSubscriptionResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantCancelStripeSubscriptionResponseBody.json
             */
            readonly $schema?: string;
            error?: string;
        };
        TenantEntitlement: {
            description: string | null;
            /** @enum {string} */
            entitlement_type: "consumable" | "non_consumable" | "subscription";
            id: string;
            metadata: string;
            name: string;
            /** Format: int64 */
            period_ms: number | null;
            products: components["schemas"]["TenantProducts"];
        };
        TenantEntitlementProduct: {
            description: string | null;
            id: string;
            metadata: string;
            name: string;
            product_id: string;
        };
        TenantGoCardlessBillingRequestFlowInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantGoCardlessBillingRequestFlowInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            failure_redirect_url: string;
            product_id: string;
            prorated_product_id?: string;
            /** @enum {string} */
            proration_mode?: "upgrade" | "downgrade";
            redirect_url: string;
        };
        TenantGoCardlessBillingRequestFlowResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantGoCardlessBillingRequestFlowResponseBody.json
             */
            readonly $schema?: string;
            error?: string;
            url: string;
        };
        TenantIdentifyUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantIdentifyUserInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
        };
        TenantIdentifyUserResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantIdentifyUserResponseBody.json
             */
            readonly $schema?: string;
            customer_id?: string;
            error?: string;
        };
        TenantListEntitlementsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListEntitlementsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["TenantEntitlement"][] | null;
            error?: string;
        };
        TenantListGocardlessProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListGocardlessProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SubscriptionGocardlessProduct"][] | null;
            error?: string;
        };
        TenantListOfferingsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListOfferingsResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["TenantOfferingsWithEntitlements"][] | null;
            error?: string;
        };
        TenantListProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["TenantProduct"][] | null;
            error?: string;
        };
        TenantListStripeProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListStripeProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SubscriptionStripeProduct"][] | null;
            error?: string;
        };
        TenantOfferingEntitlement: {
            description: string | null;
            entitlement_type: string;
            id: string;
            /** Format: int32 */
            level: number;
            name: string;
        };
        TenantOfferingsWithEntitlements: {
            /** Format: date-time */
            created_at: string;
            description: string | null;
            entitlements: components["schemas"]["TenantOfferingEntitlement"][] | null;
            id: string;
            name: string;
        };
        TenantProduct: {
            description: string | null;
            entitlement_id: string;
            id: string;
            metadata: string;
            name: string;
            product_id: string;
            store: string;
        };
        TenantProducts: {
            appstore: components["schemas"]["TenantEntitlementProduct"];
            gocardless: components["schemas"]["TenantEntitlementProduct"];
            playstore: components["schemas"]["TenantEntitlementProduct"];
            stripe: components["schemas"]["TenantEntitlementProduct"];
        };
        TenantServerGetCustomerInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantServerGetCustomerInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            /** @default prod */
            environment: string | null;
        };
        TenantServerGetCustomerResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantServerGetCustomerResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["GetCustomerExtendedInfoByEmailRow"];
            error?: string;
        };
        TenantServerGetCustomerV2ResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantServerGetCustomerV2ResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["CustomerEntitlements"];
            error?: string;
        };
        TenantStripeCheckoutInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantStripeCheckoutInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            failure_redirect_url: string;
            product_id: string;
            prorated_product_id?: string;
            /** @enum {string} */
            proration_mode?: "upgrade" | "downgrade";
            redirect_url: string;
        };
        TenantStripeCheckoutResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantStripeCheckoutResponseBody.json
             */
            readonly $schema?: string;
            error?: string;
            url: string;
        };
        TenantSyncPlayStorePastPurchasesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantSyncPlayStorePastPurchasesInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            past_purchases: components["schemas"]["PlayStorePastPurchase"][] | null;
        };
        TenantSyncPlayStorePastPurchasesResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantSyncPlayStorePastPurchasesResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["TenantSyncPlayStorePurchaseResponseData"];
            error?: string;
        };
        TenantSyncPlayStorePurchaseResponseData: {
            products?: components["schemas"]["TenantSyncProduct"][] | null;
        };
        TenantSyncProduct: {
            description: string | null;
            entitlement_id: string;
            id: string;
            name: string;
            product_id: string;
            receipt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-tenant-server-customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantServerGetCustomerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantServerGetCustomerResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-server-customers": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                sandbox?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCustomerResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-server-gocardless-cancel-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCancelGoCardlessSubscriptionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCancelGoCardlessSubscriptionResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-server-stripe-cancel-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCancelStripeSubscriptionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCancelStripeSubscriptionResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-server-v2-customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantServerGetCustomerInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantServerGetCustomerV2ResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-entitlements-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantActiveEntitlementsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantActiveEntitlementsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-entitlements-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListEntitlementsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-gocardless-billing-request-flow-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantGoCardlessBillingRequestFlowInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantGoCardlessBillingRequestFlowResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-gocardless-products-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListGocardlessProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantIdentifyUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantIdentifyUserResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListOfferingsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-playstore-sync-purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantSyncPlayStorePastPurchasesInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSyncPlayStorePastPurchasesResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-products": {
        parameters: {
            query?: never;
            header?: {
                "api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-stripe-checkout-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantStripeCheckoutInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantStripeCheckoutResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-stripe-products-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListStripeProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-subscriptions-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantActiveSubscriptionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantActiveSubscriptionResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
