/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenant/entitlements/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant entitlements by environment */
        get: operations["get-tenant-entitlements-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/gocardless/products/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant gocardless products by environment */
        get: operations["get-tenant-gocardless-products-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant products */
        get: operations["get-tenant-products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/stripe/checkout/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant stripe checkout by environment */
        post: operations["post-tenant-stripe-checkout-by-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/stripe/products/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant stripe products by environment */
        get: operations["get-tenant-stripe-products-by-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/subscriptions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post tenant subscriptions active */
        post: operations["post-tenant-subscriptions-active"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        StorableSubscription: {
            /** Format: int64 */
            expires_at: number;
            id: string;
            product_id: string;
            renewal_status: string;
            status: string;
            store: string;
        };
        SubscriptionGocardlessProduct: {
            checkout_url: string;
            currency: string;
            description?: string;
            formatted_price: string;
            id: string;
            name: string;
            /** Format: int32 */
            price: number;
        };
        SubscriptionStripePrice: {
            currency: string;
            formattedPrice: string;
            id: string;
            /** Format: double */
            price: number;
            unitLabel: string;
        };
        SubscriptionStripeProduct: {
            active: boolean;
            /** Format: int64 */
            created: number;
            deleted?: boolean;
            description?: string;
            id: string;
            images: string[] | null;
            livemode: boolean;
            metadata: {
                [key: string]: string;
            };
            name: string;
            object: string;
            price: components["schemas"]["SubscriptionStripePrice"];
            shippable?: boolean;
            statement_descriptor?: string;
            type: string;
            unit_label?: string;
            /** Format: int64 */
            updated: number;
            url?: string;
        };
        TenantActiveSubscriptionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveSubscriptionInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
        };
        TenantActiveSubscriptionResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantActiveSubscriptionResponseBody.json
             */
            readonly $schema?: string;
            data?: components["schemas"]["StorableSubscription"];
            error?: string;
        };
        TenantEntitlement: {
            description: string | null;
            id: string;
            metadata: string;
            name: string;
            /** Format: int64 */
            period_ms: number;
            products: components["schemas"]["TenantProducts"];
        };
        TenantEntitlementProduct: {
            description: string | null;
            id: string;
            metadata: string;
            name: string;
            product_id: string;
        };
        TenantListEntitlementsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListEntitlementsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["TenantEntitlement"][] | null;
            error?: string;
        };
        TenantListGocardlessProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListGocardlessProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SubscriptionGocardlessProduct"][] | null;
            error?: string;
        };
        TenantListProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["TenantProduct"][] | null;
            error?: string;
        };
        TenantListStripeProductsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantListStripeProductsResponseBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["SubscriptionStripeProduct"][] | null;
            error?: string;
        };
        TenantProduct: {
            description: string | null;
            entitlement_id: string;
            id: string;
            metadata: string;
            name: string;
            product_id: string;
            store: string;
        };
        TenantProducts: {
            appstore: components["schemas"]["TenantEntitlementProduct"];
            gocardless: components["schemas"]["TenantEntitlementProduct"];
            playstore: components["schemas"]["TenantEntitlementProduct"];
            stripe: components["schemas"]["TenantEntitlementProduct"];
        };
        TenantStripeCheckoutInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantStripeCheckoutInputBody.json
             */
            readonly $schema?: string;
            customer_email: string;
            failure_redirect_url: string;
            product_id: string;
            redirect_url: string;
        };
        TenantStripeCheckoutResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TenantStripeCheckoutResponseBody.json
             */
            readonly $schema?: string;
            error?: string;
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-tenant-entitlements-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListEntitlementsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-gocardless-products-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListGocardlessProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-products": {
        parameters: {
            query?: never;
            header?: {
                "api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-stripe-checkout-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantStripeCheckoutInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantStripeCheckoutResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tenant-stripe-products-by-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListStripeProductsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-tenant-subscriptions-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantActiveSubscriptionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantActiveSubscriptionResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
